[[Readline]]
arch = "aarch64"
git-tree-sha1 = "30454a7d4f5531fc2382ec870292d716be4194ef"
os = "macos"

    [[Readline.download]]
    sha256 = "99a08602c3764ee91d020e01c8abb7f96305941ba6d78d02d09a89adce6a4465"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.aarch64-apple-darwin.tar.gz"
[[Readline]]
arch = "aarch64"
git-tree-sha1 = "7dc20b9747872b931356b8b830f69f0641be497c"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "da7982fd10e2e3b6e4efde0d7c3c6e7e73265d22f821309ae200b7977670aa05"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.aarch64-linux-gnu.tar.gz"
[[Readline]]
arch = "aarch64"
git-tree-sha1 = "b08fa1867b446d8d47f396241549f735c878d774"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "76fc81405bbd5ce146b2974fc5253af4a7010efd68536e36d4bc5221258aaf90"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.aarch64-linux-musl.tar.gz"
[[Readline]]
arch = "aarch64"
git-tree-sha1 = "0294e3b162789ee18b2874ae3a29127171741523"
os = "freebsd"

    [[Readline.download]]
    sha256 = "47b9c4d3bd9df75c7ee4b5dd61bc2bb8894ebac7423f489c9bebe79b83b91719"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.aarch64-unknown-freebsd.tar.gz"
[[Readline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ac083affabbb5ad43cc6658534695da430d23c8d"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "73b5be5715fc056fbfe5d365b9600924755494269d04935eb2b48fc1dc1893d4"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.armv6l-linux-gnueabihf.tar.gz"
[[Readline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "039190cbf9993190cb5b84aee2abc618a4002ce5"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "e3ac79f3700db79f1989d50bb37a2cd1022f6d352f3e0ea1175eecf2d685541d"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.armv6l-linux-musleabihf.tar.gz"
[[Readline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ccecbb0c930628b64fda6739ebb08527062e156"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "42e7d1a4d1a2f1d147863571324531e189e530d32dac980d69c9a78820ccc49e"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.armv7l-linux-gnueabihf.tar.gz"
[[Readline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "016dc6c6da7be2464f396d15aae669064fe8cfd4"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "d34289ba49a9b1865379cfb7a03544bd6df0a0208862a56caf53af6a7bdd9790"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.armv7l-linux-musleabihf.tar.gz"
[[Readline]]
arch = "i686"
git-tree-sha1 = "87757ed20de560018f7ee54498eb5992536db5c5"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "b85a66768c462433f5464bd538526a56bc601a2b4cfa64b26688a2438b92e615"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.i686-linux-gnu.tar.gz"
[[Readline]]
arch = "i686"
git-tree-sha1 = "d30691bde8a8eb89ad180dab50daa929d53efe3b"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "ba9d8b0ff591b9a5201aa061b6ff34d3ea3b5e8239d06a041525d701e8981d78"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.i686-linux-musl.tar.gz"
[[Readline]]
arch = "i686"
git-tree-sha1 = "f3fcba87970464e26519dd46c241e0c6197291f1"
os = "windows"

    [[Readline.download]]
    sha256 = "5969a09b9dbefb674beaf8eb2e3356d3dffeee78c42a234d2ef7fdb3d9422082"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.i686-w64-mingw32.tar.gz"
[[Readline]]
arch = "powerpc64le"
git-tree-sha1 = "059b5fb0a6250d4ea0b9fc120330a95215c0cd14"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "0e16eb71c120dfd16cd09f146c5747f7c668182f145d34f007c65566ddb30c75"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.powerpc64le-linux-gnu.tar.gz"
[[Readline]]
arch = "riscv64"
git-tree-sha1 = "120c264b91fb03e68a678fcf8ae470b5a368804c"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "7a58ce7d9eed8e38468cfd6d8efd6c0a67026e7b240a7839150165e78678f843"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.riscv64-linux-gnu.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "94a166419d539d0693e270c2a7cb5c1d2aa62ffd"
os = "macos"

    [[Readline.download]]
    sha256 = "8e472d9e31db18d803158b94f26fe035291c4124c73de3b59b3b21d072123282"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.x86_64-apple-darwin.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "b2615156eadd07cea1a8d9c5b02ebe9bb2ef1f3b"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "ca24636f1520168836ce88b07cc7c9239b086b87d03558144a88d22989ac8e25"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.x86_64-linux-gnu.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "ed1850dd379de8df16545e4c4fa44f37fc6ae0dc"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "658f0c731641c06b5cdfc07612be79db155101af8c2ab2facadc55ddadcfd8d3"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.x86_64-linux-musl.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "19f55622856c3085941c27ece0b032a8d95e0643"
os = "freebsd"

    [[Readline.download]]
    sha256 = "ef6ca0e7c4ab6e2101d7a1ee0cdd388d4eea8202b04e981c265c344f5f99deaa"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.x86_64-unknown-freebsd.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "3d27a5f197aa6107b0ccb820c657a6d5dd7e129b"
os = "windows"

    [[Readline.download]]
    sha256 = "c31916aa6936e865b52c1cda1a8d626d4c1c4c3475901a19d2fc1f551a575177"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.3+0/Readline.v8.3.3.x86_64-w64-mingw32.tar.gz"
