[[Readline]]
arch = "aarch64"
git-tree-sha1 = "fed825b07246a7a7bc34d4be8fe51b5c51fdb8c0"
os = "macos"

    [[Readline.download]]
    sha256 = "c5ebc66ff2787260d07fb0a1e9758fe0cd98d41675ccf7d868f1a7a69ecd9e45"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.aarch64-apple-darwin.tar.gz"
[[Readline]]
arch = "aarch64"
git-tree-sha1 = "f5279a8d7fc306e2f9222db8bcea15ccf1d454b2"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "fc6cad75926d83548ddb56b7dbd023b2a16e5544ecb00b6409ad1a6b31d18100"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.aarch64-linux-gnu.tar.gz"
[[Readline]]
arch = "aarch64"
git-tree-sha1 = "ae0a67e2595e612bfa9e68f9c5cf97afe28aa3a9"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "c16c031e64c2979000ba76e6b9c4fcfceedbd784ee78e47f49c4494016955e40"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.aarch64-linux-musl.tar.gz"
[[Readline]]
arch = "aarch64"
git-tree-sha1 = "bd9a80490928e05d479b96fd3fc00166aa9c759e"
os = "freebsd"

    [[Readline.download]]
    sha256 = "619f73c94f5307bc5bc53a4e5b8c439c0989d75d0064a9a504e7381426472ff8"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.aarch64-unknown-freebsd.tar.gz"
[[Readline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "69dc93adc2902202db58b30643db24702b5f801b"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "37c7791a498a15494285b3023d677326d898518a1ef7cd70ce562d28426abbb8"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.armv6l-linux-gnueabihf.tar.gz"
[[Readline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9abe2ecdee1eb36537a747018fca5f89beaa4685"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "07c203e19c34c19bc26f18036d9336af86dff46c039d5c9b5f1c5eaab07bb6ab"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.armv6l-linux-musleabihf.tar.gz"
[[Readline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "75afa72956a43e69152d29c66ba604316a9ea7e7"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "0ee841eae256c7fcef34ba0c66c98d207c09c9196d6a91266bbc511ac1b6a5f0"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Readline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a0df04f8494867f94b61d0719d22b0b337b1aecd"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "1ba9ee21ad90b121436b8fdd73d4f66d403b13979d98dd069f7f57d3e9887875"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.armv7l-linux-musleabihf.tar.gz"
[[Readline]]
arch = "i686"
git-tree-sha1 = "b83669280a36959bcafd4c50d9f0501d3a393501"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "799800b8a80e666e500c7633d9d3102c37730604a321000dea3b7fb44bdd8b63"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.i686-linux-gnu.tar.gz"
[[Readline]]
arch = "i686"
git-tree-sha1 = "749dbde284ddb90a09a6db0d90dc13d348904a52"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "e6d47f571dbbba938049a60c6f7124c4374e102f6c0b54d0de0cbbd93fcb809c"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.i686-linux-musl.tar.gz"
[[Readline]]
arch = "i686"
git-tree-sha1 = "38045c241f9ef048536d8a19895dd4b43753d99d"
os = "windows"

    [[Readline.download]]
    sha256 = "0b25504283f4479c8da011db1a4c82571bd059478b3b459f619dbdebc0e0215b"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.i686-w64-mingw32.tar.gz"
[[Readline]]
arch = "powerpc64le"
git-tree-sha1 = "eefe770267722be446239f1df17e63e7a5b70971"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "53abbbe8ef449947aabe4dad5a9ed09fa73cf7a521056ee00f0a57b74b102491"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.powerpc64le-linux-gnu.tar.gz"
[[Readline]]
arch = "riscv64"
git-tree-sha1 = "f433253aac4257f1cd84294c27cf9ba79eaa5282"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "eb75854f3db394a3a6bd53be10879cd8d05b621ec64038a7d66fa93ffbc6aa4b"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.riscv64-linux-gnu.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "9e537aa664a8b715316a0a0893222f486f2fe561"
os = "macos"

    [[Readline.download]]
    sha256 = "c2801115ed9d96be40aafcf66d518c3b5ad8a6ec01ca9364c56cc7bb60ed75d0"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.x86_64-apple-darwin.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "0c1a62870778ff433b41277a621a0a552f43a082"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "c935e1be2926b8d643df2eee66f2a69561467004df197e967641876dac670b46"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.x86_64-linux-gnu.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "da66ed08606da8b5f815ac8780340cdf00965fa2"
libc = "musl"
os = "linux"

    [[Readline.download]]
    sha256 = "14dace1212c903b2a4e910e7797bb20d20b0b9dd079bbd2abd34fb99e8a8c67d"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.x86_64-linux-musl.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "bfab6623c577d6c6891d4ff77331de6f39d91472"
os = "freebsd"

    [[Readline.download]]
    sha256 = "0c459b49c5a9225a37a94554f12053dae9316050264fa3c32cc09a44e25b4f3e"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.x86_64-unknown-freebsd.tar.gz"
[[Readline]]
arch = "x86_64"
git-tree-sha1 = "cd7edba4470fa9e7ff29b878d0ca990a04eb1a5c"
os = "windows"

    [[Readline.download]]
    sha256 = "43b10111502f837575af66761f7644fc1bf2e73648b2c06c6bc5127b9c84f49b"
    url = "https://github.com/JuliaBinaryWrappers/Readline_jll.jl/releases/download/Readline-v8.3.0+0/Readline.v8.3.0.x86_64-w64-mingw32.tar.gz"
